In [3]:
import numpy as np

dist_covered = np.array([[2,4,6,8],[3,6,9,12]])

print("The distance covered by the 2 cars in 4 different rides are: ")
print("-------------------------------------------------------------")
print(dist_covered)

The distance covered by the 2 cars in 4 different rides are: 
-------------------------------------------------------------
[[ 2  4  6  8]
 [ 3  6  9 12]]


In [4]:
dist_covered[0,0] 

2

In [5]:
dist_covered[:,2:]

array([[ 6,  8],
       [ 9, 12]])

# Conditional Selection

- <, > , <=, >= , ==, !=

In [6]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [7]:
print(dist_covered > 5)

[[False False  True  True]
 [False  True  True  True]]


Note: whenever you use comparison operators on numpy arrays, it would always return only a boolean set of values

In [8]:
condition1 = dist_covered > 5 #greater than

print(dist_covered[condition1])
print(type(dist_covered[condition1]))

[ 6  8  6  9 12]
<class 'numpy.ndarray'>


In [11]:
condition2 = dist_covered < 4 #lesser than

print(dist_covered[condition2])

[2 3]


In [12]:
dist_covered[dist_covered >=8] #greater than or equal to

array([ 8,  9, 12])

In [13]:
dist_covered[dist_covered <=4] #less than or equal to

array([2, 4, 3])

In [39]:
print(dist_covered[dist_covered == 6]) # equal to
print(dist_covered[dist_covered != 6]) #not equal to

[6 6]
[ 2  4  8  3  9 12]


In [15]:
dist_covered[dist_covered != 6] #not equal to

array([ 2,  4,  8,  3,  9, 12])

In [17]:
print("The total number of rides in which the distance covered is greater than 6 kms: ")
print(dist_covered[dist_covered>6].size)

The total number of rides in which the distance covered is greater than 6 kms: 
3


**How to perform multiple condition checks?**

- &,|

In [18]:
dist_covered[np.where((dist_covered>4) & (dist_covered<=9))]

array([6, 8, 6, 9])

In [37]:
dist_covered[np.where((dist_covered == 5) | (dist_covered>7))]

array([ 8,  9, 12])

Note : use & to implement the and condition in numpy arrays, use | to implement the or condition in numpy arrays

# Universal functions in numpy

In [21]:
num_array = np.array([4,9,16,25,36])
print(num_array)

[ 4  9 16 25 36]


In [23]:
# math operations
print("Square root of the num_array values are: ")
print(np.sqrt(num_array))

Square root of the num_array values are: 
[2. 3. 4. 5. 6.]


In [24]:
print("Sum of the num_array values are: ")
print(np.sum(num_array))

Sum of the num_array values are: 
90


In [25]:
print("Maximum value amongst all the values of the num_array is: ")
print(np.max(num_array))

Maximum value amongst all the values of the num_array is: 
36


In [26]:
print("Minimum value amongst all the values of the num_array is: ")
print(np.min(num_array))

Minimum value amongst all the values of the num_array is: 
4


In [28]:
print("Average(mean) value of the num_Array is : ")
print(np.mean(num_array))

Average(mean) value of the num_Array is : 
18.0


In [29]:
print("Median value of the num_Array is : ")
print(np.median(num_array))

Median value of the num_Array is : 
16.0


In [30]:
print("Variance value of the num_Array is : ")
print(np.var(num_array))

Variance value of the num_Array is : 
130.8


In [31]:
num_array2 = np.array([1.75,2.6,3.4])

In [33]:
print("The rounded off values of num_array2 are : ")
print(np.round(num_array2))

The rounded off values of num_array2 are : 
[2. 3. 3.]


In [34]:
print("The floor values of num_array2 are :")
print(np.floor(num_array2))

The floor values of num_array2 are :
[1. 2. 3.]


In [35]:
print("The ceil values of num_array2 are :")
print(np.ceil(num_array2))

The ceil values of num_array2 are :
[2. 3. 4.]


In [36]:
print("The rounded off values of num_array2 are : ")
print(np.round(num_array2 , decimals= 1))

The rounded off values of num_array2 are : 
[1.8 2.6 3.4]


In [19]:
# trigonometric-------------------
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])

# Compute the sine of each angle
sine_values = np.sin(angles)
print(sine_values)  # Output: [ 0.  1.  0. -1.]

# Compute the cosine of each angle
cosine_values = np.cos(angles)
print(cosine_values)  # Output: [ 1.  0. -1.  0.]

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]


In [20]:
# bit twiddling functions
# Create an array with finite and infinite values
# infinite function
arr = np.array([1, 2, np.inf, -np.inf, np.nan, 3])

# Use numpy.isfinite to test for finite values
result = np.isfinite(arr)

print(result)

[ True  True False False False  True]


In [21]:
# usecase of isfinite function------------------
# Create an array with finite and infinite values
arr = np.array([1, 2, np.inf, -np.inf, np.nan, 3])

# Get a boolean array indicating which elements are finite
finite_mask = np.isfinite(arr)

# Use the mask to filter the finite values
finite_values = arr[finite_mask]

print(finite_values)

[1. 2. 3.]


In [22]:
# ---------------------------comparison functions----------------------------------------------------------------------------
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 5])

result = np.equal(a, b)
print(result)  # Output: [ True  True  True False]

a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 1, 3])

result = np.greater(a, b)
print(result)  # Output: [False False  True  True]

a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 4, 5])

result = np.less(a, b)
print(result)  # Output: [False False  True  True]

[ True  True  True False]
[False False  True  True]
[False False  True  True]


In [25]:
# ----------------------------------bitwise operations-------------------------------------------

a = np.array([0b1100, 0b1010, 0b1111])  # Binary representations: 12, 10, 15
b = np.array([0b1010, 0b1100, 0b1010])  # Binary representations: 10, 12, 10

result = np.bitwise_and(a, b)
print(result)  # Output: [ 8  8 10]
# Binary result: [0b1000, 0b1000, 0b1010]
print(np.bitwise_and(9,10))

[ 8  8 10]
8


In [31]:
# log function----------------------------------------------------------------
x = np.log ([1,np.e, 2]) # The np.log function is applied element-wise to each element of the array
print(x)

[0.         1.         0.69314718]


In [32]:
# difference between -inf and nan----------------------------------------------
# Calculate the natural logarithm of zero
log_zero = np.log(0)
print("Logarithm of 0:", log_zero)  # Output: -inf

# Calculate an invalid operation resulting in NaN
nan_example = np.sqrt(-1)
print("Square root of -1:", nan_example)  # Output: nan

# Check if they are NaN
print("Is -inf NaN?", np.isnan(log_zero))  # Output: False
print("Is NaN NaN?", np.isnan(nan_example))  # Output: True

# Check if they are infinite
print("Is -inf infinite?", np.isinf(log_zero))  # Output: True
print("Is NaN infinite?", np.isinf(nan_example))  # Output: False

Logarithm of 0: -inf
Square root of -1: nan
Is -inf NaN? False
Is NaN NaN? True
Is -inf infinite? True
Is NaN infinite? False


C:\Users\hp\AppData\Local\Temp\ipykernel_8236\4088827407.py:3: RuntimeWarning: divide by zero encountered in log
  log_zero = np.log(0)
C:\Users\hp\AppData\Local\Temp\ipykernel_8236\4088827407.py:7: RuntimeWarning: invalid value encountered in sqrt
  nan_example = np.sqrt(-1)


In [37]:
# Logic functions--------------------------------------------------------------------

a = np.array([True, True, False, False])
b = np.array([True, False, True, False])

result = np.logical_and(a, b)
print(result)  # Output: [ True False False False]

arr = np.array([True, True, False])
result = arr.all()
print(result)  # Output: False

arr = np.array([[True, True], [True, False]])
result = arr.all()
print(result)  # Output: False

arr = np.array([[True, True], [True, False]])
result = arr.all(axis=0) # through col
print(result)  # Output: [ True False]

arr = np.array([1, 2, 3, 4])
result = (arr > 0).all()
print(result)  # Output: True

arr = np.array([[True, False], [True, False]])
print(np.any(arr))  # o/p = true

arr = np.array([[True, False], [True, False]])
result = np.any(arr, axis=0)  # o/p : [ True False]
print(result)


[ True False False False]
False
False
[ True False]
True
True
[ True False]
[ True False]


In [27]:
np.mod(np.arange(0,8),5)

array([0, 1, 2, 3, 4, 0, 1, 2], dtype=int32)

# How to split and stack Numpy arrays

- hsplit(), vsplit()
- hstack(), vstack()

In [12]:
dist_covered.resize(2,4)
print(dist_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [13]:
np.hsplit(dist_covered, 2) # splits the array column wise into n equal arrays

[array([[2, 4],
        [3, 6]]),
 array([[ 6,  8],
        [ 9, 12]])]

In [14]:
np.hsplit(dist_covered, 4)

[array([[2],
        [3]]),
 array([[4],
        [6]]),
 array([[6],
        [9]]),
 array([[ 8],
        [12]])]

In [15]:
np.vsplit(dist_covered, 2)# splits the array row wise into n equal arrays

[array([[2, 4, 6, 8]]), array([[ 3,  6,  9, 12]])]

From above, we can infer that the hsplit(),vplit() functions only divide the numpy array equally column wise, row wise respectively.

In [16]:
print(dist_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [17]:
num_array = np.array([[1,2,3,4],[15,16,17,18]])

print(num_array)

[[ 1  2  3  4]
 [15 16 17 18]]


In [18]:
dist_covered.shape

(2, 4)

In [50]:
num_array.shape

(2, 4)

In [51]:
print("Result of stacking dist_covered array and num_array using hstack() is : ")
print(np.hstack((dist_covered,num_array)))

Result of stacking dist_covered array and num_array using hstack() is : 
[[ 2  4  6  8  1  2  3  4]
 [ 3  6  9 12 15 16 17 18]]


Note : hstack combines/stacks the two arrays along the columns. so, as long as the number of rows are same in both the arrays, the hstack() method would work.

In [52]:
print("Result of stacking dist_covered array and num_array using vstack() is : ")
print(np.vstack((dist_covered,num_array)))

Result of stacking dist_covered array and num_array using vstack() is : 
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 1  2  3  4]
 [15 16 17 18]]


Note : vstack combines/stacks the two arrays along the rows. so, as long as the number of columns are same in both the arrays, the vstack() method would work.

# End of section